# Generated by Django 2.0.7 on 2019-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='at_a_glance',
            field=models.CharField(default='blog summary', max_length=100),
        ),
    ]
